security:
    encoders:
        App\Entity\Users: auto
        App\Entity\Admin: auto


    providers:
        app_user_provider:
            entity:
                class: App\Entity\Users
                property: username
        app_admin_provider:
            entity:
                class: App\Entity\Admin
                property: username

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        vendor:
            pattern: /admin
            anonymous: ~
            provider: app_admin_provider
            lazy: true
            json_login:
                check_path: /api/admin/login

            logout:
                path: /api/admin/logout
                target: /

        main:
            pattern:   /
            anonymous: ~
            provider: app_user_provider
            lazy: true
            json_login:
                check_path: /api/user/login

            logout:
                path: /api/user/logout
                target: /

    access_control:
        - { path: ^/home, roles: ROLE_USER }
        - { path: ^/home, roles: ROLE_ADMIN }
        # - { path: ^/profile, roles: ROLE_USER }